# Define preprocessing pipeline
pipeline:
  resize:
    width: 302  # roughly maintains aspect ratio
    height: 226
    interp: bicubic
  crop:
    width: 224
    height: 224
  augmentation:
    method: numpy
    fold: 8
  train_split: .8
